Fix module2dbk.mathml2svg failure for exercise math
This is the content that is causing module2dbk.mathml2svg failure:

```
<link class="os-embed" url="#ost/api/ex/k12phys-ch10-ex028"/>
```

This specific bit of math in the exercise is what caused the error:

```
<span data-math="\beta">\beta</span>
```

```
Traceback (most recent call last):
  File "./a.py", line 20, in ?
    collectiondbk2pdf.__doStuff('col10002_1.9_complete/', 'physics')
  File "collectiondbk2pdf.py", line 96, in __doStuff
    return collection2pdf(collection_dir, print_style, output_pdf, pdfgen, temp_dir, verbose)
  File "collectiondbk2pdf.py", line 70, in collection2pdf
    dbk, newFiles = collection2dbk.convert(p, collxml, modules, temp_dir, svg2png=False, math2svg=True, reduce_quality=reduce_quality)
  File "collection2dbk.py", line 79, in convert
    reduce_quality, benchmark=benchmark)
  File "/home/karen/oer.exports/module2dbk.py", line 454, in convert
    xml, newFiles2, errors = transform(xml, origAndNewFiles, **params)
  File "/home/karen/oer.exports/module2dbk.py", line 339, in mathml2svg
    if compare_trees(returned_mathml, expected_mathml):
  File "/home/karen/oer.exports/module2dbk.py", line 125, in compare_trees
    return all(compare_trees(c1, c2) for c1, c2 in zip(e1, e2))
  File "/home/karen/oer.exports/module2dbk.py", line 114, in all
    for element in iterable:
  File "/home/karen/oer.exports/module2dbk.py", line 125, in <generator expression>
    return all(compare_trees(c1, c2) for c1, c2 in zip(e1, e2))
  File "/home/karen/oer.exports/module2dbk.py", line 125, in compare_trees
    return all(compare_trees(c1, c2) for c1, c2 in zip(e1, e2))
  File "/home/karen/oer.exports/module2dbk.py", line 114, in all
    for element in iterable:
  File "/home/karen/oer.exports/module2dbk.py", line 125, in <generator expression>
    return all(compare_trees(c1, c2) for c1, c2 in zip(e1, e2))
  File "/home/karen/oer.exports/module2dbk.py", line 121, in compare_trees
    if e1.text != e2.text: raise ValueError("Text does not match. Returned %s Expected %s" % (repr(e1.text), repr(e2.text)))
ValueError: Text does not match. Returned ' &#946; ' Expected u' \u03b2 '
```

Fixed by making the `returned_mathml` use unicode instead of xml
entities.