:fire: numpy
because it had problems installing on OS X and is not used for testing.

```
Running numpy-1.13.3/setup.py -q bdist_egg --dist-dir
/var/folders/c5/zr_3pn3j2rx_20tfg_7fnjm80000gn/T/easy_install-wG0FKQ/num
py-1.13.3/egg-dist-tmp-9q_Fqt
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules _winreg, win32api or win32con are
installed.
non-existing path in 'numpy/distutils': 'site.cfg'
Could not locate executable gfortran
Could not locate executable f95
Could not locate executable f90
Could not locate executable f77
Could not locate executable xlf90
Could not locate executable xlf
Could not locate executable ifort
Could not locate executable ifc
Could not locate executable g77
Could not locate executable g95
Could not locate executable pgfortran
don't know how to compile Fortran code on platform 'posix'
_configtest.c:1:5: warning: incompatible redeclaration of library
function 'exp' [-Wincompatible-library-redeclaration]
int exp (void);
    ^
_configtest.c:1:5: note: 'exp' is a builtin with type 'double (double)'
1 warning generated.
_configtest.c:1:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
```